/* eslint-disable @typescript-eslint/no-unused-vars */

import type { NextPage } from "next";
import Head from "next/head";
import { Button, Drawer, Panel } from "rsuite";


const Home: NextPage = (props) => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen gap-4">
      <Button>
        Click me
      </Button>
      
      <Panel>
      <Button appearance="primary">
        Click me
      </Button>
      <span>Text pour tester tailwind dark Mode</span>
      </Panel>
     <Drawer
       open={true}
       onClose={()=>{
        console.log('exit');
        
       }}
     >
       <Drawer.Header>
         <Drawer.Title>Drawer Title</Drawer.Title>
       </Drawer.Header>
       <Drawer.Body>
         <span>This is a body</span>
       </Drawer.Body>
       <Drawer.Footer>
         <Button appearance="primary">Confirm</Button>
         <Button appearance="subtle">Cancel</Button>
       </Drawer.Footer>
     </Drawer>
     
     
      </main>
    </>
  );
};



export default Home;
